### ISSUE TITLE
TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by arndom** [Pik-9/schluessel#6]
I added the import credentials from 'schluessel' after editing the json that was generated  but i keep  getting `TypeError: fs.existsSync is not a function` in my browser

**Comment by Pik-9** [comment]
Hi @arndom,

you get this error, because you try to access a file from the browser with the `fs` module, which is not possible due to security considerations. The `fs` module only exists in Node.js.

The point is: `schluessel` is not meant to be run in the browser - it's for **Node.js only**. It's meant to store credentials on the _backend_ server. Using it to encrypt credentials in the frontend (in the browser) is not it's purpose.

I hope this clarifies things a bit.

Regards
🂩
